version: '3.9'
services:
  movies:
    image: hanvitha/pythonlife
    ports:
      - "84:80"
    deploy:
      replicas: 3
  dth:
    image: hanvitha/devops:v2
    ports:
      - "85:80"
    deploy:
      replicas: 3
  recharge:
    image: hanvitha/aws:v3
    ports:
      - "86:80"
    deploy:
      replicas: 3
  paytm:
    image: hanvitha/paytm:v4
    ports:
      - "87:80"
    deploy:
      replicas: 3

